- id: depsync
  name: depsync
  description: Check or fix TOML operator spacing
  entry: depsync
  language: python
  types: [toml]
  additional_dependencies: ["tomlkit", "packaging", "."]

- id: toml-sort
  name: toml-sort
  entry: run toml-sort
  language: python
  types: [toml]
  additional_dependencies: ["toml-sort==0.24.2", "."]
