repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

-   repo: https://github.com/hmsgit/depsync
    rev: v0.1.0
    hooks:
    -   id: toml-sort
        args: [--all, --in-place, --ignore-case, --sort-first, "name,version"]
    -   id: depsync
    -   id: depsync
        args: [--fix]
