name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Which part of the version to bump (major, minor, patch)"
        required: false
        default: "patch"

permissions:
  contents: write

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          latest=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Latest tag: $latest"
          echo "tag=$latest" >> "$GITHUB_OUTPUT"

      - name: Bump version
        id: bump
        run: |
          tag="${{ steps.get_tag.outputs.tag }}"
          bump="${{ github.event.inputs.bump || 'patch' }}"
          version=${tag#v}
          IFS='.' read -r major minor patch <<< "$version"

          case "$bump" in
            major) major=$((major + 1)); minor=0; patch=0 ;;
            minor) minor=$((minor + 1)); patch=0 ;;
            patch|*) patch=$((patch + 1)) ;;
          esac

          new="v$major.$minor.$patch"
          echo "New version: $new"
          echo "new_tag=$new" >> "$GITHUB_OUTPUT"

      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git tag "${{ steps.bump.outputs.new_tag }}"
          git push origin "${{ steps.bump.outputs.new_tag }}"
